#!/bin/sh
# Generate a random maze with maze_gen and render it to PDF.
#
# Usage:
#   ./scripts/make_maze.sh <width> <height> [output.pdf]
#   ./scripts/make_maze.sh 15 20              → maze_15x20.txt, maze_15x20.pdf
#   ./scripts/make_maze.sh 10 10 my_maze.pdf  → maze_10x10.txt, my_maze.pdf
#
# The program that creates the maze is ./maze_gen (from maze_gen.c).

set -e

ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"

MAZE_GEN=./maze_gen
CONVERT_SCRIPT=./scripts/convert.sh

if [ $# -lt 2 ]; then
    echo "Usage: $0 <width> <height> [output.pdf]"
    echo "  width, height = maze size in cells (e.g. 15 20)"
    echo "  output.pdf    = optional PDF filename (default: maze_WxH.pdf)"
    echo ""
    echo "The maze is generated by: $MAZE_GEN (maze_gen.c)"
    exit 1
fi

W=$1
H=$2
PDF="${3:-maze_${W}x${H}.pdf}"
MAZE_FILE="maze_${W}x${H}.txt"

if [ ! -x "$MAZE_GEN" ]; then
    echo "Error: $MAZE_GEN not found. Build it with: gcc -o maze_gen maze_gen.c"
    exit 1
fi

echo "Generating ${W}x${H} maze..."
"$MAZE_GEN" "$W" "$H" "$MAZE_FILE"

if [ ! -s "$MAZE_FILE" ]; then
    echo "Error: maze file is empty."
    exit 1
fi

echo "Rendering to PDF..."
if [ -x "$CONVERT_SCRIPT" ]; then
    "$CONVERT_SCRIPT" "$MAZE_FILE" cell_size 0.25 "$PDF"
    echo "Done. Maze: $MAZE_FILE  PDF: $PDF"
else
    echo "Error: $CONVERT_SCRIPT not found or not executable."
    exit 1
fi
